### ISSUE TITLE
Error while installing (Ubuntu VPS)

### ISSUE THREAD

**Issue by cv1000b** [thesparklabs/openvpn-configuration-generator#1]
Hi,

I've tried to install the OpenVPN Configuration Generator on three different VPS:s with Ubuntu 16.04 on them, but all resulting in the same error.

`root@testerver:~# sudo dpkg -i openvpn-configuration-generator_1.0.2-1.deb`
`Selecting previously unselected package openvpn-configuration-generator.`
`(Reading database ... 92804 files and directories currently installed.)`
`Preparing to unpack openvpn-configuration-generator_1.0.2-1.deb ...`
`Unpacking openvpn-configuration-generator (1.0.2-1) ...`
`Setting up openvpn-configuration-generator (1.0.2-1) ...`
`rm: cannot remove '/usr/bin/openvpn-generate': No such file or directory`
`dpkg: error processing package openvpn-configuration-generator (--install):`
 `subprocess installed post-installation script returned error exit status 1`
`Errors were encountered while processing: openvpn-configuration-generator`

Is there an easy fix available for this issue? Thanks! :)

**Comment by trametheka** [comment]
Hi @cv1000b,

Try running:

`sudo touch /usr/bin/openvpn-generate`

And then running the installer again. We'll get a fixed installer up as soon as we can.

**Comment by cv1000b** [comment]
That worked great. Thank you very much for the quick reply!

**Comment by trametheka** [comment]
Thanks for the report, a fixed installer has been uploaded. Cheers!
