### ISSUE TITLE
Usage of the tool under Windows

### ISSUE THREAD

**Issue by renegade2k** [thesparklabs/openvpn-configuration-generator#6]
Hi.
It's totaly unclear, how to use the tool under Windows.
I download the msi, install it (what is the path?!) and then i have neither a desktop icon, nore an entry in the start-menu.
So ... can't even find a folder in "program files" where the tool should be.

**Comment by jbekkema** [comment]
Hi renegade2k,

Documentation for Windows can be found at:
https://www.sparklabs.com/support/kb/article/creating-certificates-and-keys-for-your-openvpn-server/#windows

Cheers,
James
