### ISSUE TITLE
No internet connection

### ISSUE THREAD

**Issue by Mahdi321** [thesparklabs/openvpn-configuration-generator#9]
After connection to vpn on client. only available IP on pinging is vpn server IP (Note below profile is not testable on other networks (Server IP is Private))
Client: Linux
Server: Windows 10
[client1@25.78.183.0.zip](https://github.com/thesparklabs/openvpn-configuration-generator/files/3365880/client1%4025.78.183.0.zip)
[server.zip](https://github.com/thesparklabs/openvpn-configuration-generator/files/3365881/server.zip)

**Comment by trametheka** [comment]
I'm afraid we only offer support for our Viscosity client. I recommend you look into your routing setup though, we have some information here that may help you - https://sparklabs.com/support/kb/article/routing-traffic-for-websites-applications/
